### ISSUE TITLE
Game width is "jumpy" on Windows

### ISSUE THREAD

**Issue by epidemian** [epidemian/snake#3]
This is how it looks on Chrome on Windows:

![snake-score-moving](https://user-images.githubusercontent.com/722544/56617083-5214d280-65f5-11e9-90fb-0cd71f687b90.gif)

This problem was originally reported by @rosald on #2.

**Comment by epidemian** [comment]
@rosald, i've run the game on a machine with Windows and yeah, this issue is totally reproducible :/

I can't think of anything to do though. It seems to be related with the way Windows renders Braille characters. Other systems render all Braille characters with the same width (i had tested the game on Linux mostly, but also on macOS and Android), but Windows seems to render blank Braille character ([U+2800](https://www.fileformat.info/info/unicode/block/braille_patterns/list.htm)) a bit narrower than other Braille characters (which have at least one dot). So it makes this jumpy effect at the of the game board as the snake moves sideways.

I'll leave this issue open for now, though i can't think of a way to fix it. The problem may be inherent to the way WIndows renders fonts... But maybe someone comes up with a solution :) ... If not, i'm going to close it as a wontfix :sweat_smile: 

---

BTW, running this game on WIndows made me realize i had broken compatibility with IE. I fixed tha on 5af76fb7cef7316dba9130b2ebbacd4823fe6350. So thanks for the report! :relaxed:

**Comment by epidemian** [comment]
This issue is outdated. Since then, browsers have started escaping whitespace characters on the URL, making the game unplayable on the addressbar. So, the game being "jumpy" is no longer a relevant issue.

**Comment by rosald** [comment]
![20231114-160850](https://github.com/epidemian/snake/assets/35028438/eb8f2378-d6a5-4066-8ce9-af633aea2998)
what a pity. imaginative project!
pic is mac chrome

**Comment by epidemian** [comment]
@rosald thanks for the kind words :)

yeah, text rendering issues are a pain :sweat_smile:
