### ISSUE TITLE
Speed adjustment controls

### ISSUE THREAD

**Issue by dchan3** [epidemian/snake#7]
I think there should be controls to adjust the speed of the game. It might be rather fast for some. I can contribute with a pull request if possible.

**Comment by epidemian** [comment]
:thinking: What do you have in mind?

I'd rather keep the content on the page as minimal as possible, to keep as much of the game confined to the URL as possible. The existing `?` and `!` controls on the page already add quite a bit of noise IMO...

Also, i think controlling the speed of the game completely could make the score itself a bit pointless. Like, what would be the point of scoring 156 (the maximum theoretical score) if one could lower the game speed to a crawl? Maybe having an "easy" difficulty (or a "turtle mode", or something that doesn't sound so negative) could make sense. And make it be a toggeable button on the UI, similar to this button on the Transmission torrent client:

![image](https://user-images.githubusercontent.com/722544/73621031-3ffba200-4613-11ea-87ae-4f96878914e5.png)

Some simple solution like that might be worth it. But, if i'd have to choose between more options on the game, or keeping it simple and challenging, i think i'd err on the later.

**Comment by epidemian** [comment]
I'm closing this as out of scope for the project. I think the idea has its merits, but i would like to keep the UI pretty minimal, and TBH i'm not looking forward to adding more stuff to this project that no longer renders properly on most browsers' address bars :/
